[features]
seeds = false
skip-lint = false

[programs.localnet]
reflex_pvp_escrow = "GMq3D9QQ8LxjcftXMnQUmffRoiCfczbuUoASaS7pCkp7"

[programs.devnet]
reflex_pvp_escrow = "GMq3D9QQ8LxjcftXMnQUmffRoiCfczbuUoASaS7pCkp7"


[provider]
cluster = "devnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "anchor test"
