[features]
seeds = false
skip-lint = false

[programs.localnet]
reflex_pvp_escrow = "7HNevHHofq8N52W8sqzxznn4PJ2rXwEdtU5WHWUMZLhn"

[programs.devnet]
reflex_pvp_escrow = "7HNevHHofq8N52W8sqzxznn4PJ2rXwEdtU5WHWUMZLhn"


[provider]
cluster = "devnet"
wallet = "/home/daniel/.config/solana/id.json"

[scripts]
test = "anchor test"